"""empty message

Revision ID: dbb51ee5e6ca
Revises: dd063c90c5ec
Create Date: 2020-01-26 09:59:10.450802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb51ee5e6ca'
down_revision = 'dd063c90c5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
