"""empty message

Revision ID: dd063c90c5ec
Revises: fa8449f627cf
Create Date: 2020-01-26 09:43:59.865178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd063c90c5ec'
down_revision = 'fa8449f627cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('is_true', sa.Boolean(), nullable=True))
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('answer_quiestion_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.drop_column('answer', 'quiestion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('quiestion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_quiestion_id_fkey', 'answer', 'question', ['quiestion_id'], ['id'])
    op.drop_column('answer', 'question_id')
    op.drop_column('answer', 'is_true')
    # ### end Alembic commands ###
